process.roles=broker
node.id=1
listeners=PLAINTEXT://localhost:9092
advertised.listeners=PLAINTEXT://localhost:9092
log.dirs=demos/migration/data/broker1
controller.quorum.voters=100@localhost:9093,101@localhost:9094,102@localhost:9095
controller.listener.names=CONTROLLER
num.partitions=3
default.replication.factor=3
min.insync.replicas=2
offsets.topic.replication.factor=3
inter.broker.protocol.version=3.9
