process.roles=controller
node.id=100
controller.quorum.voters=100@localhost:9093,101@localhost:9094,102@localhost:9095
listeners=CONTROLLER://localhost:9093
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
log.dirs=data/controller1
zookeeper.connect=localhost:2181,localhost:2182,localhost:2183
zookeeper.metadata.migration.enable=true
