process.roles=controller
node.id=101
controller.quorum.voters=100@localhost:9093,101@localhost:9094,102@localhost:9095
listeners=CONTROLLER://localhost:9094
controller.listener.names=CONTROLLER
log.dirs=data/controller2
